// AUTO-GENERATED BY vite-plugin-stone-auto-registry
            export const stoneComponentRegistry = {
              "s-card": () => import("./components/Card"),
  "mini-counter": () => import("./components/MiniCounter"),
  "nav-bar": () => import("./components/NavBar")
            } as const;
            