import type { Plugin, ViteDevServer } from "vite";
import { promises as fs } from "node:fs";
import { join, relative, resolve, sep, posix, dirname } from "node:path";
import { kebabCase } from "scule";

interface StoneAutoRegistryOptions {
  componentsDir: string;
  output: string;
  extensions?: string[];
}

function toPosixPath(p: string) {
  return p.split(sep).join(posix.sep);
}

function getCustomElementName(file: string) {
  const base = file.replace(/\.[^.]+$/, "");
  let kebab = kebabCase(base);
  if (!kebab.includes("-")) kebab = `s-${kebab}`;
  return kebab;
}

async function generateRegistry(options: StoneAutoRegistryOptions) {
  const { componentsDir, output, extensions = [".ts", ".tsx"] } = options;
  const absDir = resolve(process.cwd(), componentsDir);

  // Use exact output path as specified
  const absOutput = resolve(process.cwd(), output);
  const outputDir = dirname(absOutput);

  try {
    // Check if components directory exists
    await fs.access(absDir);
  } catch (error) {
    // Create components directory if it doesn't exist
    await fs.mkdir(absDir, { recursive: true });
    console.log(`[stone] Created components directory at ${componentsDir}`);

    // Early return since there are no components yet
    // Ensure output directory exists
    await fs.mkdir(outputDir, { recursive: true });

    // Create an empty registry if no components exist yet
    const content = `// AUTO-GENERATED BY vite-plugin-stone-auto-registry
export const stoneComponentRegistry = {} as const;
`;
    await fs.writeFile(absOutput, content, "utf-8");
    console.log(
      `[stone-auto-registry] Generated empty component registry at ${output}`
    );
    return;
  }

  const files = await fs.readdir(absDir);
  const componentFiles = files.filter((f) =>
    extensions.some((ext) => f.endsWith(ext))
  );

  // Generate mapping: { "s-card": "./components/Card" }
  const entries = await Promise.all(
    componentFiles.map(async (file) => {
      const name = getCustomElementName(file);

      // Compute path relative to output file's directory
      let relPath = relative(outputDir, join(absDir, file));
      // Always use posix-style (forward slashes) for imports
      relPath = toPosixPath(relPath);
      // Remove .ts or .tsx extension for Vite import
      relPath = relPath.replace(/\.[tj]sx?$/, "");
      if (!relPath.startsWith(".")) relPath = `./${relPath}`;

      return `  "${name}": () => import("${relPath}")`;
    })
  );

  const content = `// AUTO-GENERATED BY vite-plugin-stone-auto-registry
export const stoneComponentRegistry = {
${entries.join(",\n")}
} as const;
`;

  // Ensure output directory exists
  await fs.mkdir(outputDir, { recursive: true });

  await fs.writeFile(absOutput, content, "utf-8");
  console.log(`stone-auto-registry] Generated component registry at ${output}`);
}

export default function stoneAutoRegistry(
  options: StoneAutoRegistryOptions
): Plugin {
  return {
    name: "vite-plugin-stone-auto-registry",
    enforce: "pre",
    configResolved: async () => {
      await generateRegistry(options);
    },
    async buildStart() {
      await generateRegistry(options);
    },
    configureServer(server: ViteDevServer) {
      // Generate the registry initially when dev server starts
      generateRegistry(options).catch((err) => {
        console.error("[stone] Error generating component registry:", err);
      });

      // Watch for changes
      server.watcher.on("change", async (file) => {
        if (file.startsWith(resolve(process.cwd(), options.componentsDir))) {
          await generateRegistry(options);
          server.ws.send({ type: "full-reload" });
        }
      });
    },
  };
}
